name: "CI"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    # This also runs nix-build.
    - uses: cachix/cachix-action@v6
      with:
        name: srid
        # signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # Only needed for private caches
        # authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    # This builds neuron, as well as run tests
    - run: nix-env -if "https://github.com/srid/neuron/archive/736107f8dd12ed514b6956c9e938437b5bd5fa49.tar.gz"
    - name: Debug Action
      uses: hmarr/debug-action@v1.0.0
    - run: neuron -d . rib
    - name: push
      uses: github-actions-x/commit@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        push_branch: 'gh-pages-test'
        commit_message: 'publish'
